package app

import (
	"strings"
	"testing"
)

const testChangelog = `# Changelog

<!-- generated by git-cliff -->

## [v2.6.2] - 2026-03-27

### Security

- *(deps)* Upgrade golang.org/x/image to v0.38.0 for GO-2026-4815

### Bug Fixes

- Align gofumpt formatting with golangci-lint v2.1.6

## [v2.6.1] - 2026-03-24

### Features

- *(device)* Add device import UI
- *(cloudsource)* OAuth2 PKCE loopback handler

### Bug Fixes

- Use ldflags for credentials

## [v2.5.4] - 2026-03-22

### Documentation

- Update README
`

func TestGetChangelog(t *testing.T) {
	store, err := newTestStore(t)
	if err != nil {
		t.Fatalf("failed to create test store: %v", err)
	}
	defer func() { _ = store.Close() }()
	a := NewApp(store)
	a.ChangelogRaw = testChangelog
	result := a.GetChangelog()
	if result != testChangelog {
		t.Error("GetChangelog should return the full changelog")
	}
}

func TestGetChangelogForCurrentVersion(t *testing.T) {
	store, err := newTestStore(t)
	if err != nil {
		t.Fatalf("failed to create test store: %v", err)
	}
	defer func() { _ = store.Close() }()
	a := NewApp(store)
	a.ChangelogRaw = testChangelog
	a.Version = "v2.6.2"
	result := a.GetChangelogForCurrentVersion()
	if result == "" {
		t.Fatal("expected non-empty changelog for v2.6.2")
	}
	if !strings.Contains(result, "Upgrade golang.org/x/image") {
		t.Error("expected v2.6.2 security entry in result")
	}
	if strings.Contains(result, "OAuth2 PKCE") {
		t.Error("should not contain v2.6.1 entries")
	}
}

func TestGetChangelogForCurrentVersion_DevVersion(t *testing.T) {
	store, err := newTestStore(t)
	if err != nil {
		t.Fatalf("failed to create test store: %v", err)
	}
	defer func() { _ = store.Close() }()
	a := NewApp(store)
	a.ChangelogRaw = testChangelog
	a.Version = "dev"
	result := a.GetChangelogForCurrentVersion()
	if result != "" {
		t.Error("dev version should return empty changelog")
	}
}

func TestShouldShowWhatsNew(t *testing.T) {
	store, err := newTestStore(t)
	if err != nil {
		t.Fatalf("failed to create test store: %v", err)
	}
	defer func() { _ = store.Close() }()
	a := NewApp(store)
	a.Version = "v2.6.2"
	if !a.ShouldShowWhatsNew() {
		t.Error("should show on first launch")
	}
	a.AcknowledgeWhatsNew()
	if a.ShouldShowWhatsNew() {
		t.Error("should not show after acknowledgement")
	}
}

func TestShouldShowWhatsNew_DevVersion(t *testing.T) {
	store, err := newTestStore(t)
	if err != nil {
		t.Fatalf("failed to create test store: %v", err)
	}
	defer func() { _ = store.Close() }()
	a := NewApp(store)
	a.Version = "dev"
	if a.ShouldShowWhatsNew() {
		t.Error("dev version should never show what's new")
	}
}
