package app

import (
	"cullsnap/internal/logger"
	"strings"
)

func (a *App) GetChangelog() string {
	logger.Log.Debug("GetChangelog called", "contentLength", len(a.ChangelogRaw))
	return a.ChangelogRaw
}

func (a *App) GetChangelogForCurrentVersion() string {
	if a.Version == "" || a.Version == "dev" {
		logger.Log.Debug("Skipping changelog for dev version", "version", a.Version)
		return ""
	}
	marker := "## [" + a.Version + "]"
	idx := strings.Index(a.ChangelogRaw, marker)
	if idx == -1 {
		logger.Log.Debug("Version not found in changelog", "version", a.Version)
		return ""
	}
	rest := a.ChangelogRaw[idx+len(marker):]
	nextIdx := strings.Index(rest, "\n## [v")
	if nextIdx == -1 {
		section := a.ChangelogRaw[idx:]
		if footerIdx := strings.Index(section, "<!-- generated by git-cliff -->"); footerIdx != -1 {
			section = strings.TrimRight(section[:footerIdx], "\n")
		}
		logger.Log.Debug("Returning changelog section", "version", a.Version, "bytes", len(section))
		return section
	}
	section := a.ChangelogRaw[idx : idx+len(marker)+nextIdx]
	section = strings.TrimRight(section, "\n")
	logger.Log.Debug("Returning changelog section", "version", a.Version, "bytes", len(section))
	return section
}

func (a *App) ShouldShowWhatsNew() bool {
	if a.Version == "" || a.Version == "dev" {
		logger.Log.Debug("ShouldShowWhatsNew: false (dev build)")
		return false
	}
	lastSeen, _ := a.store.GetConfig("lastSeenVersion")
	show := lastSeen != a.Version
	logger.Log.Debug("ShouldShowWhatsNew check", "lastSeen", lastSeen, "current", a.Version, "show", show)
	return show
}

func (a *App) AcknowledgeWhatsNew() {
	logger.Log.Debug("AcknowledgeWhatsNew", "version", a.Version)
	if err := a.store.SetConfig("lastSeenVersion", a.Version); err != nil {
		logger.Log.Error("Failed to store lastSeenVersion", "error", err)
	}
}
