// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgeWhatsNew() {
  return window['go']['app']['App']['AcknowledgeWhatsNew']();
}

export function AuthenticateCloudSource(arg1) {
  return window['go']['app']['App']['AuthenticateCloudSource'](arg1);
}

export function CancelDeduplicate() {
  return window['go']['app']['App']['CancelDeduplicate']();
}

export function CancelImport(arg1) {
  return window['go']['app']['App']['CancelImport'](arg1);
}

export function CancelMirror(arg1, arg2) {
  return window['go']['app']['App']['CancelMirror'](arg1, arg2);
}

export function CheckDedupStatus(arg1) {
  return window['go']['app']['App']['CheckDedupStatus'](arg1);
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function ClearAllCache() {
  return window['go']['app']['App']['ClearAllCache']();
}

export function ClearCloudMirror(arg1, arg2) {
  return window['go']['app']['App']['ClearCloudMirror'](arg1, arg2);
}

export function ClearImportCache(arg1) {
  return window['go']['app']['App']['ClearImportCache'](arg1);
}

export function DeleteCachedAlbum(arg1, arg2) {
  return window['go']['app']['App']['DeleteCachedAlbum'](arg1, arg2);
}

export function DisconnectCloudSource(arg1) {
  return window['go']['app']['App']['DisconnectCloudSource'](arg1);
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function ExportPhotos(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportPhotos'](arg1, arg2, arg3);
}

export function GetAboutInfo() {
  return window['go']['app']['App']['GetAboutInfo']();
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetCacheStats() {
  return window['go']['app']['App']['GetCacheStats']();
}

export function GetChangelog() {
  return window['go']['app']['App']['GetChangelog']();
}

export function GetChangelogForCurrentVersion() {
  return window['go']['app']['App']['GetChangelogForCurrentVersion']();
}

export function GetCloudSources() {
  return window['go']['app']['App']['GetCloudSources']();
}

export function GetConnectedDevices() {
  return window['go']['app']['App']['GetConnectedDevices']();
}

export function GetExportedStatus(arg1) {
  return window['go']['app']['App']['GetExportedStatus'](arg1);
}

export function GetImportStats() {
  return window['go']['app']['App']['GetImportStats']();
}

export function GetMirrorStats() {
  return window['go']['app']['App']['GetMirrorStats']();
}

export function GetPhotoEXIF(arg1) {
  return window['go']['app']['App']['GetPhotoEXIF'](arg1);
}

export function GetRatingsForDirectory(arg1) {
  return window['go']['app']['App']['GetRatingsForDirectory'](arg1);
}

export function GetRecentFolders() {
  return window['go']['app']['App']['GetRecentFolders']();
}

export function GetSelections(arg1) {
  return window['go']['app']['App']['GetSelections'](arg1);
}

export function ImportFromDevice(arg1) {
  return window['go']['app']['App']['ImportFromDevice'](arg1);
}

export function ListCachedAlbums() {
  return window['go']['app']['App']['ListCachedAlbums']();
}

export function ListCloudAlbums(arg1) {
  return window['go']['app']['App']['ListCloudAlbums'](arg1);
}

export function MirrorCloudAlbum(arg1, arg2, arg3) {
  return window['go']['app']['App']['MirrorCloudAlbum'](arg1, arg2, arg3);
}

export function OpenFolderInFinder(arg1) {
  return window['go']['app']['App']['OpenFolderInFinder'](arg1);
}

export function OpenLog() {
  return window['go']['app']['App']['OpenLog']();
}

export function PreloadThumbnails(arg1) {
  return window['go']['app']['App']['PreloadThumbnails'](arg1);
}

export function ResetAppConfig() {
  return window['go']['app']['App']['ResetAppConfig']();
}

export function RestartForUpdate() {
  return window['go']['app']['App']['RestartForUpdate']();
}

export function SaveAppConfig(arg1) {
  return window['go']['app']['App']['SaveAppConfig'](arg1);
}

export function ScanAndDeduplicate(arg1, arg2) {
  return window['go']['app']['App']['ScanAndDeduplicate'](arg1, arg2);
}

export function ScanDirectory(arg1) {
  return window['go']['app']['App']['ScanDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectExportDirectory() {
  return window['go']['app']['App']['SelectExportDirectory']();
}

export function SetPhotoRating(arg1, arg2) {
  return window['go']['app']['App']['SetPhotoRating'](arg1, arg2);
}

export function ShouldShowWhatsNew() {
  return window['go']['app']['App']['ShouldShowWhatsNew']();
}

export function ToggleSelection(arg1, arg2, arg3) {
  return window['go']['app']['App']['ToggleSelection'](arg1, arg2, arg3);
}
