// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {app} from '../models';

export function CancelDeduplicate():Promise<void>;

export function ExportPhotos(arg1:Array<model.Photo>,arg2:string):Promise<number>;

export function GetExportedStatus(arg1:string):Promise<Record<string, boolean>>;

export function GetPhotoEXIF(arg1:string):Promise<app.PhotoEXIF>;

export function GetRatingsForDirectory(arg1:string):Promise<Record<string, number>>;

export function GetRecentFolders():Promise<Array<string>>;

export function GetSelections(arg1:string):Promise<Record<string, boolean>>;

export function GetSystemResources():Promise<app.SystemResources>;

export function GetThumbnailBase64(arg1:string):Promise<string>;

export function OpenFolderInFinder(arg1:string):Promise<void>;

export function OpenLog():Promise<void>;

export function ScanAndDeduplicate(arg1:string,arg2:number):Promise<app.DedupeResult>;

export function ScanDirectory(arg1:string):Promise<Array<model.Photo>>;

export function SelectDirectory():Promise<string>;

export function SelectExportDirectory():Promise<string>;

export function SetPhotoRating(arg1:string,arg2:number):Promise<void>;

export function ToggleSelection(arg1:string,arg2:string,arg3:boolean):Promise<void>;
