// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgeWhatsNew() {
  return window['go']['app']['App']['AcknowledgeWhatsNew']();
}

export function AuthenticateCloudSource(arg1) {
  return window['go']['app']['App']['AuthenticateCloudSource'](arg1);
}

export function CancelAIAnalysis() {
  return window['go']['app']['App']['CancelAIAnalysis']();
}

export function CancelDeduplicate() {
  return window['go']['app']['App']['CancelDeduplicate']();
}

export function ClearAIData(arg1) {
  return window['go']['app']['App']['ClearAIData'](arg1);
}

export function CancelImport(arg1) {
  return window['go']['app']['App']['CancelImport'](arg1);
}

export function CancelMirror(arg1, arg2) {
  return window['go']['app']['App']['CancelMirror'](arg1, arg2);
}

export function CheckDedupStatus(arg1) {
  return window['go']['app']['App']['CheckDedupStatus'](arg1);
}

export function CheckDeviceDependencies() {
  return window['go']['app']['App']['CheckDeviceDependencies']();
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function ClearAllCache() {
  return window['go']['app']['App']['ClearAllCache']();
}

export function ClearCloudMirror(arg1, arg2) {
  return window['go']['app']['App']['ClearCloudMirror'](arg1, arg2);
}

export function ClearImportCache(arg1) {
  return window['go']['app']['App']['ClearImportCache'](arg1);
}

export function DeleteCachedAlbum(arg1, arg2) {
  return window['go']['app']['App']['DeleteCachedAlbum'](arg1, arg2);
}

export function DisconnectCloudSource(arg1) {
  return window['go']['app']['App']['DisconnectCloudSource'](arg1);
}

export function DownloadAIModels() {
  return window['go']['app']['App']['DownloadAIModels']();
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function ExportPhotos(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportPhotos'](arg1, arg2, arg3);
}

export function GetAIResults(arg1) {
  return window['go']['app']['App']['GetAIResults'](arg1);
}

export function GetAIScoringStatus() {
  return window['go']['app']['App']['GetAIScoringStatus']();
}

export function GetAIWeights() {
  return window['go']['app']['App']['GetAIWeights']();
}

export function GetAboutInfo() {
  return window['go']['app']['App']['GetAboutInfo']();
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetCacheStats() {
  return window['go']['app']['App']['GetCacheStats']();
}

export function GetChangelog() {
  return window['go']['app']['App']['GetChangelog']();
}

export function GetChangelogForCurrentVersion() {
  return window['go']['app']['App']['GetChangelogForCurrentVersion']();
}

export function GetCloudSources() {
  return window['go']['app']['App']['GetCloudSources']();
}

export function GetConnectedDevices() {
  return window['go']['app']['App']['GetConnectedDevices']();
}

export function GetExportedStatus(arg1) {
  return window['go']['app']['App']['GetExportedStatus'](arg1);
}

export function GetImportStats() {
  return window['go']['app']['App']['GetImportStats']();
}

export function GetMirrorStats() {
  return window['go']['app']['App']['GetMirrorStats']();
}

export function GetPhotoAIScore(arg1) {
  return window['go']['app']['App']['GetPhotoAIScore'](arg1);
}

export function GetPhotoEXIF(arg1) {
  return window['go']['app']['App']['GetPhotoEXIF'](arg1);
}

export function GetRatingsForDirectory(arg1) {
  return window['go']['app']['App']['GetRatingsForDirectory'](arg1);
}

export function GetRecentFolders() {
  return window['go']['app']['App']['GetRecentFolders']();
}

export function GetSelections(arg1) {
  return window['go']['app']['App']['GetSelections'](arg1);
}

export function HideFaceCluster(arg1, arg2) {
  return window['go']['app']['App']['HideFaceCluster'](arg1, arg2);
}

export function ImportFromDevice(arg1) {
  return window['go']['app']['App']['ImportFromDevice'](arg1);
}

export function ListCachedAlbums() {
  return window['go']['app']['App']['ListCachedAlbums']();
}

export function ListCloudAlbums(arg1) {
  return window['go']['app']['App']['ListCloudAlbums'](arg1);
}

export function MergeFaceClusters(arg1, arg2) {
  return window['go']['app']['App']['MergeFaceClusters'](arg1, arg2);
}

export function MirrorCloudAlbum(arg1, arg2, arg3) {
  return window['go']['app']['App']['MirrorCloudAlbum'](arg1, arg2, arg3);
}

export function OpenFolderInFinder(arg1) {
  return window['go']['app']['App']['OpenFolderInFinder'](arg1);
}

export function OpenLog() {
  return window['go']['app']['App']['OpenLog']();
}

export function PreloadThumbnails(arg1) {
  return window['go']['app']['App']['PreloadThumbnails'](arg1);
}

export function PreloadThumbnailsForPhotos(arg1) {
  return window['go']['app']['App']['PreloadThumbnailsForPhotos'](arg1);
}

export function RenameFaceCluster(arg1, arg2) {
  return window['go']['app']['App']['RenameFaceCluster'](arg1, arg2);
}

export function ResetAppConfig() {
  return window['go']['app']['App']['ResetAppConfig']();
}

export function RestartForUpdate() {
  return window['go']['app']['App']['RestartForUpdate']();
}

export function RunAIAnalysis(arg1) {
  return window['go']['app']['App']['RunAIAnalysis'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['app']['App']['SaveAppConfig'](arg1);
}

export function ScanAndDeduplicate(arg1, arg2) {
  return window['go']['app']['App']['ScanAndDeduplicate'](arg1, arg2);
}

export function ScanDirectory(arg1) {
  return window['go']['app']['App']['ScanDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectExportDirectory() {
  return window['go']['app']['App']['SelectExportDirectory']();
}

export function SetAIScoringEnabled(arg1) {
  return window['go']['app']['App']['SetAIScoringEnabled'](arg1);
}

export function SetAIWeights(arg1) {
  return window['go']['app']['App']['SetAIWeights'](arg1);
}

export function SetPhotoRating(arg1, arg2) {
  return window['go']['app']['App']['SetPhotoRating'](arg1, arg2);
}

export function ShouldShowWhatsNew() {
  return window['go']['app']['App']['ShouldShowWhatsNew']();
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function ToggleSelection(arg1, arg2, arg3) {
  return window['go']['app']['App']['ToggleSelection'](arg1, arg2, arg3);
}
