// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {model} from '../models';
import {cloudsource} from '../models';
import {device} from '../models';

export function AcknowledgeWhatsNew():Promise<void>;

export function AuthenticateCloudSource(arg1:string):Promise<void>;

export function CancelDeduplicate():Promise<void>;

export function CancelImport(arg1:string):Promise<void>;

export function CancelMirror(arg1:string,arg2:string):Promise<void>;

export function CheckDedupStatus(arg1:string):Promise<app.DedupStatus>;

export function CheckForUpdate():Promise<void>;

export function ClearAllCache():Promise<void>;

export function ClearCloudMirror(arg1:string,arg2:string):Promise<void>;

export function ClearImportCache(arg1:string):Promise<void>;

export function DeleteCachedAlbum(arg1:string,arg2:string):Promise<void>;

export function DisconnectCloudSource(arg1:string):Promise<void>;

export function DownloadUpdate():Promise<void>;

export function ExportPhotos(arg1:Array<model.Photo>,arg2:string,arg3:string):Promise<number>;

export function GetAboutInfo():Promise<app.AboutInfo>;

export function GetAppConfig():Promise<app.AppConfig>;

export function GetCacheStats():Promise<cloudsource.CacheStats>;

export function GetChangelog():Promise<string>;

export function GetChangelogForCurrentVersion():Promise<string>;

export function GetCloudSources():Promise<Array<cloudsource.CloudSourceStatus>>;

export function GetConnectedDevices():Promise<Array<device.Device>>;

export function GetExportedStatus(arg1:string):Promise<Record<string, boolean>>;

export function GetImportStats():Promise<app.ImportStats>;

export function GetMirrorStats():Promise<app.MirrorStats>;

export function GetPhotoEXIF(arg1:string):Promise<app.PhotoEXIF>;

export function GetRatingsForDirectory(arg1:string):Promise<Record<string, number>>;

export function GetRecentFolders():Promise<Array<string>>;

export function GetSelections(arg1:string):Promise<Record<string, boolean>>;

export function ImportFromDevice(arg1:string):Promise<string>;

export function ListCachedAlbums():Promise<Array<cloudsource.CachedAlbum>>;

export function ListCloudAlbums(arg1:string):Promise<Array<cloudsource.Album>>;

export function MirrorCloudAlbum(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenFolderInFinder(arg1:string):Promise<void>;

export function OpenLog():Promise<void>;

export function PreloadThumbnails(arg1:string):Promise<Array<model.Photo>>;

export function ResetAppConfig():Promise<app.AppConfig>;

export function RestartForUpdate():Promise<void>;

export function SaveAppConfig(arg1:app.AppConfig):Promise<void>;

export function ScanAndDeduplicate(arg1:string,arg2:number):Promise<app.DedupeResult>;

export function ScanDirectory(arg1:string):Promise<Array<model.Photo>>;

export function SelectDirectory():Promise<string>;

export function SelectExportDirectory():Promise<string>;

export function SetPhotoRating(arg1:string,arg2:number):Promise<void>;

export function ShouldShowWhatsNew():Promise<boolean>;

export function ToggleSelection(arg1:string,arg2:string,arg3:boolean):Promise<void>;
