// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDeduplicate() {
  return window['go']['app']['App']['CancelDeduplicate']();
}

export function CheckDedupStatus(arg1) {
  return window['go']['app']['App']['CheckDedupStatus'](arg1);
}

export function ExportPhotos(arg1, arg2) {
  return window['go']['app']['App']['ExportPhotos'](arg1, arg2);
}

export function GetExportedStatus(arg1) {
  return window['go']['app']['App']['GetExportedStatus'](arg1);
}

export function GetPhotoEXIF(arg1) {
  return window['go']['app']['App']['GetPhotoEXIF'](arg1);
}

export function GetRatingsForDirectory(arg1) {
  return window['go']['app']['App']['GetRatingsForDirectory'](arg1);
}

export function GetRecentFolders() {
  return window['go']['app']['App']['GetRecentFolders']();
}

export function GetSelections(arg1) {
  return window['go']['app']['App']['GetSelections'](arg1);
}

export function GetSystemResources() {
  return window['go']['app']['App']['GetSystemResources']();
}

export function OpenFolderInFinder(arg1) {
  return window['go']['app']['App']['OpenFolderInFinder'](arg1);
}

export function OpenLog() {
  return window['go']['app']['App']['OpenLog']();
}

export function PreloadThumbnails(arg1) {
  return window['go']['app']['App']['PreloadThumbnails'](arg1);
}

export function ScanAndDeduplicate(arg1, arg2) {
  return window['go']['app']['App']['ScanAndDeduplicate'](arg1, arg2);
}

export function ScanDirectory(arg1) {
  return window['go']['app']['App']['ScanDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectExportDirectory() {
  return window['go']['app']['App']['SelectExportDirectory']();
}

export function SetPhotoRating(arg1, arg2) {
  return window['go']['app']['App']['SetPhotoRating'](arg1, arg2);
}

export function ToggleSelection(arg1, arg2, arg3) {
  return window['go']['app']['App']['ToggleSelection'](arg1, arg2, arg3);
}
