// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPhotos(arg1, arg2) {
  return window['go']['main']['App']['ExportPhotos'](arg1, arg2);
}

export function GetExportedStatus(arg1) {
  return window['go']['main']['App']['GetExportedStatus'](arg1);
}

export function GetRecentFolders() {
  return window['go']['main']['App']['GetRecentFolders']();
}

export function GetSelections(arg1) {
  return window['go']['main']['App']['GetSelections'](arg1);
}

export function GetSystemResources() {
  return window['go']['main']['App']['GetSystemResources']();
}

export function OpenLog() {
  return window['go']['main']['App']['OpenLog']();
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectExportDirectory() {
  return window['go']['main']['App']['SelectExportDirectory']();
}

export function ToggleSelection(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleSelection'](arg1, arg2, arg3);
}
