// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function ExportPhotos(arg1:Array<model.Photo>,arg2:string):Promise<number>;

export function GetExportedStatus(arg1:string):Promise<Record<string, boolean>>;

export function GetRecentFolders():Promise<Array<string>>;

export function GetSelections(arg1:string):Promise<Record<string, boolean>>;

export function GetSystemResources():Promise<main.SystemResources>;

export function OpenLog():Promise<void>;

export function ScanDirectory(arg1:string):Promise<Array<model.Photo>>;

export function SelectDirectory():Promise<string>;

export function SelectExportDirectory():Promise<string>;

export function ToggleSelection(arg1:string,arg2:string,arg3:boolean):Promise<void>;
